apiVersion: v1
kind: Namespace
metadata:
  name: {{NAMESPACE}}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-depl
  namespace: {{NAMESPACE}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
        - name: monitoring-container
          image: "gcr.io/{{PROJECT_ID}}/monitoring-service:{{SHORT_SHA}}"
          ports:
            - name: http-port
              containerPort: 2137
          env:
            - name: MAILER_HOST
              valueFrom:
                configMapKeyRef:
                  name: monitoring-config
                  key: mailer_host
            - name: MAILER_PORT
              valueFrom:
                configMapKeyRef:
                  name: monitoring-config
                  key: mailer_port
            - name: MAILER_FROM
              valueFrom:
                secretKeyRef:
                  name: monitoring-secret-config
                  key: mailer_from
            - name: MAILER_PASS
              valueFrom:
                secretKeyRef:
                  name: monitoring-secret-config
                  key: mailer_pass
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: monitoring-config
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: monitoring-config
                  key: redis_port
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: monitoring-config
                  key: java_opts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-single-instance
  namespace: {{NAMESPACE}}
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: master
          image: redis:6.0.10-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: {{NAMESPACE}}
spec:
  type: LoadBalancer
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
  selector:
    app: monitoring-app
